# Generated by Django 3.1.6 on 2021-05-07 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamount', models.CharField(blank=True, max_length=50)),
                ('interest', models.CharField(blank=True, max_length=50)),
                ('security', models.TextField(blank=True, max_length=5000)),
                ('installments', models.CharField(blank=True, max_length=50)),
                ('irate', models.CharField(blank=True, max_length=50, null=True)),
                ('adate', models.CharField(blank=True, max_length=50, null=True)),
                ('edate', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.CharField(blank=True, max_length=50, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
