# Generated by Django 3.1.6 on 2021-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
