# Generated by Django 3.1.6 on 2021-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30, unique=True)),
                ('lastname', models.CharField(max_length=30, unique=True)),
                ('dob', models.CharField(max_length=30, unique=True)),
                ('nin', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=30, unique=True)),
                ('phaddress', models.CharField(max_length=30, unique=True)),
                ('poaddress', models.CharField(max_length=30, unique=True)),
                ('occupation', models.CharField(max_length=30, unique=True)),
                ('gnumber', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
