# Generated by Django 3.1.6 on 2021-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210507_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='gnumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='nin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='phaddress',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='poaddress',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
